name: Run Unit Tests
on:
  push:
    branches:
      - main
    paths:
      - '*.js'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tests/*.js'
      - 'openAI/*.js'
      - 'utils/*'
      - 'data/*'
  pull_request:
    branches:
      - main
    paths:
      - '*.js'
      - 'package.json'
      - 'pnpm-lock.yaml'
      - 'tests/*.js'
      - 'openAI/*.js'
      - 'utils/*'
      - 'data/*'
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test